name: pgadmin
image: docker.io/dpage/pgadmin4:latest
description: pgAdmin web UI for the lerd Postgres service
ports:
  - "8081:80"
environment:
  PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
  PGADMIN_DEFAULT_PASSWORD: lerd
  PGADMIN_CONFIG_SERVER_MODE: "False"
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
depends_on:
  - postgres
dashboard: http://localhost:8081
files:
  - target: /pgadmin4/servers.json
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Lerd Postgres",
            "Group": "Servers",
            "Host": "lerd-postgres",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "SSLMode": "prefer",
            "PassFile": "/pgpass"
          }
        }
      }
  - target: /pgpass
    mode: "0600"
    chown: true
    content: |
      lerd-postgres:5432:*:postgres:lerd
  - target: /pgadmin4/config_local.py
    content: |
      X_FRAME_OPTIONS = ''
      ENHANCED_COOKIE_PROTECTION = False
      WTF_CSRF_CHECK_DEFAULT = False
