//go:build linux

package dns

import (
	"os"
	"testing"
)

// --- parseNameservers ---

func TestParseNameservers_realServers(t *testing.T) {
	f := writeTempFile(t, `
# Generated by NetworkManager
nameserver 192.168.1.1
nameserver 8.8.8.8
`)
	got := parseNameservers(f)
	want := []string{"192.168.1.1", "8.8.8.8"}
	assertSliceEqual(t, got, want)
}

func TestParseNameservers_skipsLoopback(t *testing.T) {
	f := writeTempFile(t, `
nameserver 127.0.0.1
nameserver 127.0.0.53
nameserver ::1
nameserver 10.0.0.1
`)
	got := parseNameservers(f)
	want := []string{"10.0.0.1"}
	assertSliceEqual(t, got, want)
}

func TestParseNameservers_onlyLoopback(t *testing.T) {
	f := writeTempFile(t, "nameserver 127.0.0.53\n")
	got := parseNameservers(f)
	if len(got) != 0 {
		t.Errorf("expected empty, got %v", got)
	}
}

func TestParseNameservers_missingFile(t *testing.T) {
	got := parseNameservers("/nonexistent/resolv.conf")
	if got != nil {
		t.Errorf("expected nil for missing file, got %v", got)
	}
}

func TestParseNameservers_commentsIgnored(t *testing.T) {
	f := writeTempFile(t, `
# This is a comment
; another comment
search example.com
nameserver 1.1.1.1
`)
	got := parseNameservers(f)
	want := []string{"1.1.1.1"}
	assertSliceEqual(t, got, want)
}

// --- helpers ---

func writeTempFile(t *testing.T, content string) string {
	t.Helper()
	f, err := os.CreateTemp(t.TempDir(), "resolv-*.conf")
	if err != nil {
		t.Fatal(err)
	}
	f.WriteString(content)
	f.Close()
	return f.Name()
}

func assertSliceEqual(t *testing.T, got, want []string) {
	t.Helper()
	if len(got) != len(want) {
		t.Errorf("got %v, want %v", got, want)
		return
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("index %d: got %q, want %q", i, got[i], want[i])
		}
	}
}
